version: '2'
services:
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports: 
      - "3306:3306"
    volumes: 
      - ./db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"